export const EVENTS_PATH = "/competition/events";

export const SET_IS_FETCHING_EVENTS = "SET_IS_FETCHING_EVENTS";
export const FETCH_EVENTS_SUCCESS = "FETCH_EVENTS_SUCCESS";
export const FETCH_EVENTS_FAILURE = "FETCH_EVENTS_FAILURE";
