export const FETCH_COMPETITION_SUCCESS = "FETCH_COMPETITION_SUCCESS";
export const FETCH_COMPETITION_FAILURE = "FETCH_COMPETITION_FAILURE";
export const SET_IS_FETCHING_COMPETITION = "SET_IS_FETCHING_COMPETITION";

export const UPDATE_COMPETITION_SUCCESS = "UPDATE_COMPETITION_SUCCESS";
export const UPDATE_COMPETITION_FAILURE = "UPDATE_COMPETITION_FAILURE";
export const SET_IS_UPDATING_COMPETITION = "SET_IS_UPDATING_COMPETITION";

export const SAVE_COMPETITION_SUCCESS = "SAVE_COMPETITION_SUCCESS";
export const SAVE_COMPETITION_FAILURE = "SAVE_COMPETITION_FAILURE";
export const SET_IS_SAVING_COMPETITION = "SET_IS_SAVING_COMPETITION";

export const DELETE_COMPETITION_SUCCESS = "DELETE_COMPETITION_SUCCESS";
export const DELETE_COMPETITION_FAILURE = "DELETE_COMPETITION_FAILURE";
export const SET_IS_DELETING_COMPETITION = "SET_IS_DELETING_COMPETITION";

export const FETCH_COMPETITION_ATTENDEES_SUCCESS =
  "FETCH_COMPETITION_ATTENDEES_SUCCESS";
export const FETCH_COMPETITION_ATTENDEES_FAILURE =
  "FETCH_COMPETITION_ATTENDEES_FAILURE";
export const SET_IS_FETCHING_COMPETITION_ATTENDEES =
  "SET_IS_FETCHING_COMPETITION_ATTENDEES";

export const INVITE_COMPETITION_ATTENDEE_SUCCESS =
  "INVITE_COMPETITION_ATTENDEE_SUCCESS";
export const INVITE_COMPETITION_ATTENDEE_FAILURE =
  "INVITE_COMPETITION_ATTENDEE_FAILURE";
export const SET_IS_INVITING_COMPETITION_ATTENDEE =
  "SET_IS_INVITING_COMPETITION_ATTENDEE";

export const COMPETITION_MESSAGE_ATTENDEES_SUCCESS =
  "COMPETITION_MESSAGE_ATTENDEES_SUCCESS";
export const COMPETITION_MESSAGE_ATTENDEES_FAILURE =
  "COMPETITION_MESSAGE_ATTENDEES_FAILURE";
export const SET_IS_MESSAGING_ATTENDEES = "SET_IS_MESSAGING_ATTENDEES";

export const COMPETITION_PATH = "/competition/";
export const COMPETITION_INVITES_PATH = "/competition/invites";
export const COMPETITION_MESSAGE_ATTENDEES_PATH =
  "/competition/attendees/message";
