export const EVENTS_PATH = "/competition/events";

export const SET_IS_FETCHING_EVENTS = "SET_IS_FETCHING_EVENTS";
export const FETCH_EVENTS_SUCCESS = "FETCH_EVENTS_SUCCESS";
export const FETCH_EVENTS_FAILURE = "FETCH_EVENTS_FAILURE";

// TODO: Move to own reducer
export const SET_IS_CREATING_EVENT = "SET_IS_CREATING_EVENT";
export const CREATE_EVENT_SUCCESS = "CREATE_EVENT_SUCCESS";
export const CREATE_EVENT_FAILURE = "CREATE_EVENT_FAILURE";

export const SET_IS_DELETING_EVENT = "SET_IS_DELETING_EVENT";
export const DELETE_EVENT_SUCCESS = "DELETE_EVENT_SUCCESS";
export const DELETE_EVENT_FAILURE = "DELETE_EVENT_FAILURE";
