export const NOTIFICATIONS_PATH = "/api/notifications";
export const ON_RECEIVE_NOTIFICATION = "ON_RECEIVE_NOTIFICATION";
export const SET_IS_FETCHING_NOTIFICATIONS = "SET_IS_FETCHING_NOTIFICATIONS";
export const FETCH_NOTIFICATIONS_SUCCESS = "FETCH_NOTIFICATIONS_SUCCESS";
export const FETCH_NOTIFICATIONS_FAILURE = "FETCH_NOTIFICATIONS_FAILURE";
export const SEEN_NOTIFICATION = "SEEN_NOTIFICATION";
export const DISMISS_NOTIFICATION = "DISMISS_NOTIFICATION";
