export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export const FETCH_USER_FAILURE = "FETCH_USER_FAILURE";
export const SET_IS_FETCHING = "SET_IS_FETCHING";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAILURE = "UPDATE_USER_FAILURE";
export const SET_IS_UPDATING = "SET_IS_UPDATING";
export const SET_UPDATE_SUCCESS = "SET_UPDATE_SUCCESS";
export const CHANGE_SETTING_VALUES = "CHANGE_SETTING_VALUES";
export const RESET_SETTING_VALUES = "RESET_SETTING_VALUES";

export const SET_IS_DELETING_USER = "SET_IS_DELETING_USER";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAILURE = "DELETE_USER_FAILURE";

export const SET_IS_CHANGING_PASSWORD = "SET_IS_CHANGING_PASSWORD";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_FAILURE = "CHANGE_PASSWORD_FAILURE";

export const SET_IS_UPLOADING_AVATAR = "SET_IS_UPLOADING_AVATAR";
export const UPLOAD_AVATAR_SUCCESS = "UPLOAD_AVATAR_SUCCESS";
export const UPLOAD_AVATAR_FAILURE = "UPLOAD_AVATAR_FAILURE";

export const USER_PATH = "/api/users";
export const USER_ME_PATH = `${USER_PATH}/me`;
export const CHANGE_PASSWORD_PATH = `${USER_ME_PATH}/change_password`;
export const AUTH_PATH = "/auth";
export const SIGN_IN_PATH = `${AUTH_PATH}/sign_in`;
export const SIGN_OUT_PATH = `${AUTH_PATH}/sign_out`;
export const RESET_PASSWORD_PATH = `${AUTH_PATH}/password`;

export const SET_IS_SIGNING_IN = "SET_IS_SIGNING_IN";
export const SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS";
export const SIGN_IN_FAILURE = "SIGN_IN_FAILURE";

export const SET_IS_SIGNING_OUT = "SET_IS_SIGNING_OUT";
export const SIGN_OUT_SUCCESS = "SIGN_OUT_SUCCESS";
export const SIGN_OUT_FAILURE = "SIGN_OUT_FAILURE";
